name: Manual workflow

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Field to display'
        # Default value if no value is explicitly provided
        default: 'subscription'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  doit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: 'Prepare integration tests'
      run: |
        echo "$LOGONDATA_JSON" > $GITHUB_WORKSPACE/logon-data.json
        export LOGONDATA_FNAME=$GITHUB_WORKSPACE/logon-data.json
        INTEGRATIONTEST_DATA=$(jq -r '.${{ github.event.inputs.name }}?' $LOGONDATA_FNAME)
        echo "${{ github.event.inputs.name }} for testing: $INTEGRATIONTEST_DATA"
      env:
        LOGONDATA_JSON: ${{ secrets.INTEGRATIONTESTS_CLI_LOGONDATA_JSON }}
      shell: bash
