name: publish-to-marketplace
on:
  release:
    types: [published]
  push:
    paths:
    - '.github/workflows/publish-to-marketplace.yml'

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install or update the TFS Cross Platform Command Line Interface 
        run: npm i -g tfx-cli

      - name: Publish
        run: |
          cd marketplace
          $tag = "${{ github.event.release.name }}"
          if ($tag.StartsWith('v')) { $tag = $tag.Substring(1) }
          $ver = [System.Management.Automation.SemanticVersion]::Parse($tag)
          $ver3 = "$($ver.Major).$($ver.Minor).$($ver.Patch)"
          $jsonOverride = "`"{\`"version\`": \`"${ver3}\`"}`""
          tfx extension publish --manifest vss-extension.json --token ${{ secrets.MARKETPLACE_PAT }} --override $jsonOverride
        shell: pwsh
 